name: Update Subscription
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      subscription:
        description: 'Subscription url'
        type: string
        required: false
jobs:
  update_subscription:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          

      - name: Update Subcription
        env:
          SUB_URL: ${{ github.event.inputs.subscription }}
          SEC_URL: ${{ secrets.SUB_URL }}
        run: |
          if [ $SUB_URL ]; then curl -o new.yaml $SUB_URL; else curl -o new.yaml $SEC_URL; fi
          python merge.py
      

      - name: Package
        run: bash ./package.sh


      - name: Push
        run: |
          git add -f clash.tar.gz
          git commit -m "update clash archive"
          git push origin
  
